name: Merge main into adsk_contrib/dev

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'  # Runs every Saturday at midnight

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout adsk_contrib/dev branch
      uses: actions/checkout@v2
      with:
        ref: adsk_contrib/dev 
        fetch-depth: 0

    - name: Set up Git user
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Checkout main branch
      run: |
        git fetch origin main:main
        git checkout main

    - name: Create auxiliary branch
      run: |
        git status
        git checkout -b merge-main-to-dev-fix-${{ github.run_number }}
        git add .
        git commit --allow-empty -m "Auto merge main into adsk_contrib/dev"
        git push origin merge-main-to-dev-fix-${{ github.run_number }}

    - name: Create PR
      uses: poorva17/create-pr-action@v2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HEAD_BRANCH: merge-main-to-dev-fix-${{ github.run_number }}
        BASE_BRANCH: adsk_contrib/dev 
