name: Merge main into adsk_contrib/dev

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'  # Runs every Saturday at midnight

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout adsk_contrib/dev branch
      uses: actions/checkout@v2
      with:
        ref: main 
        fetch-depth: 0

    - name: Set up Git user
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Handle conflicts and create auxiliary branch
      run: |
        git checkout -b merge-main-to-dev-fix-${{ github.run_number }}
        git add .
        git commit --allow-empty -m "Auto merge main into adsk_contrib/dev"
        git push origin merge-main-to-dev-fix-${{ github.run_number }}

    - name: Open Pull Request if merge fails
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Merge main into adsk_contrib/dev with conflicts resolved
        branch: merge-main-to-dev-fix-${{ github.run_number }}
        base: adsk_contrib/dev
        title: Merge main into adsk_contrib/dev
        body: Handling merge conflicts between `main` and `adsk_contrib/dev`
        reviewers: ehlenl  # List of users
        labels: merge-conflicts
