name: Merge main into adsk_contrib/dev

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'  # Runs every Saturday at midnight

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main 
        fetch-depth: 0

    - name: Set up Git user
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"



    - name: Open Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: Merge main into adsk_contrib/dev
        branch: adsk_contrib/dev
        title: Merge main into adsk_contrib/dev
        body: Proposed merge between `main` and `adsk_contrib/dev`
        reviewers: ashwinbhat,zicher3d,ppenenko  # List of users
        labels: merge
